### ISSUE TITLE
Crashes on re-connect after getaddr failed errror

### ISSUE THREAD

**Issue by ntokash** [thedmd/pianobar-windows-binaries#11]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pianobar.exe
  Application Version:	1.0.0.0
  Application Timestamp:	51f508a5
  Fault Module Name:	pianobar.exe
  Fault Module Version:	1.0.0.0
  Fault Module Timestamp:	51f508a5
  Exception Code:	c0000005
  Exception Offset:	00045c27
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	80a7
  Additional Information 4:	80a7ccd5015bce3d41120fe057d4f98f

**Comment by thedmd** [comment]
@ntokash Can you try 2015.12.05 release?

**Comment by thedmd** [comment]
Curl/libwaitress was replaced in Windows port by WinHTTP. So, there are no more calls to g
