### ISSUE TITLE
No sound despite appearing to play correctly

### ISSUE THREAD

**Issue by dwierenga** [thedmd/pianobar-windows-binaries#12]
I'm able to login and select a playlist, and see a track supposedly begin to play.  However, I'm not able to hear any sound.

**Comment by dwierenga** [comment]
More detail:
- After an hour and a half or so, the same track is still playing. It never advances to a second track.
- I'm able to play Pandora via Internet Explorer, Chrome, and Firefox.
- my terminal is able to create sounds (beeps) successfully (cmd.exe and powershell.exe).

**Comment by dwierenga** [comment]
The binary at 85fa96d74a works fine.

**Comment by LiVIU245** [comment]
I have the same problem.

**Comment by chadkennedyonline** [comment]
Same here. I believe the song is not being played, however. The binary at 85fa96d shows total song time and remaining time counting down. The latest binary shows neither, leading me to believe the song is not actually being played.

**Comment by x89codered89x** [comment]
Same

**Comment by thedmd** [comment]
@dwierenga Can you try 2015.12.05 release?

**Comment by LiVIU245** [comment]
@thedmd It's working,thank you!
