### ISSUE TITLE
Windows 10 64bit

### ISSUE THREAD

**Issue by ravensorrow** [thedmd/pianobar-windows-binaries#14]
When trying to run the Windows binary in a command console, I get the following error;

E:\>pianobar
This version of E:\Users\Chris\Container\bin\pianobar.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

E:\>

**Comment by thedmd** [comment]
I wonder if this is because of Windows XP compatibility.

**Comment by ravensorrow** [comment]
![2015-12-06_7-36-07](https://cloud.githubusercontent.com/assets/3761618/11613383/53ffde2c-9bec-11e5-92b6-1ed4e3fcd057.png)

Is the issue I get know with the most recent version of the application (updated 21hrs ago)

**Comment by thedmd** [comment]
@ravensorrow Can you tell me what SHA-1 or any other common checksum of exe downloaded by you is?

**Comment by ravensorrow** [comment]
E:\Users\Chris\Container\bin>sha1sum.exe pianobar.exe
6214f4d961c6a58aaa58eea389b34a0135c88209 *pianobar.exe

E:\Users\Chris\Container\bin>sha256sum.exe pianobar.exe
e2458f5773b1229b428f03e9710992ef5f0209b11d9bfb5012dc316e46567822 *pianobar.exe

E:\Users\Chris\Container\bin>

**Comment by thedmd** [comment]
SHA-1 hashes I got for latest releases are:
`a30c1fe08976cb301e2203d23df634d572b23f15 *pianobar.exe 2010.12.10 618496 bytes`
`31dd6c9a939a219d6b059351e01cf64ae38ee461 *pianobar.exe 2010.12.05 623616 bytes` 

Can you verify these once more?

**Comment by ravensorrow** [comment]
Checksums generated by ExactFile 1.0.0.15
http://www.exactfile.com
12/11/2015 6:54:28 AM

E:\Users\Chris\Container\bin\pianobar.exe
22966 bytes

SHA1: 6214f4d961c6a58aaa58eea389b34a0135c88209

I see there is a difference between what I have and what you have. I'm gonna go try and download again.

**Comment by ravensorrow** [comment]
Grabbed a zip of the whole project this time instead of just downloading the one exe.

My hash matches yours now;


E:\Users\Chris\Container\bin>exf -sha1 pianobar.exe
; Checksums generated by ExactFile Console Application 1.0.1.6 BETA
; www.ExactFile.com
; 12/11/2015 6:58:30 AM
;
a30c1fe08976cb301e2203d23df634d572b23f15 ?SHA1*pianobar.exe
; 1 files sucessfully hashed.

E:\Users\Chris\Container\bin>

and I'm able to run it.

**Comment by thedmd** [comment]
Great!
