### ISSUE TITLE
Always instantly jumping to next song

### ISSUE THREAD

**Issue by rgobo** [thedmd/pianobar-windows-binaries#15]
This started happening after during playback around 12 hours ago, I lost connection and after reconnecting it's like every song lasts 0 seconds. The stations and playlists load correctly but each song is instantly finished and the next one is started, only to be instantly replaced by the next one, etc.

I'm on Windows 10 x64. I think the issue might be related to that Windows lib Pianobar uses to play music, it used to appear in the notification area while Pianobar was running but now it's gone, I can't remember it's name. I'm using the control proxy btw.

**Comment by rgobo** [comment]
Well, it works now, I guess it was a problem on Pandora's end? LAV Splitter started and music plays as nothing ever happened.

**Comment by 96fps** [comment]
Hello, I'm having this issue since i updated to windows 10 the other day, mere hours after having no trouble on 8.1
This is happening using both the same binaries as before, as well as freshly downloaded ones.
