### ISSUE TITLE
Songs queue but don't play

### ISSUE THREAD

**Issue by Zosoled** [thedmd/pianobar-windows-binaries#16]
Previous exe worked just fine (from May 2015 I think?) but August 2015 build will not play songs. It receives the playlist and queues up a song, but it doesn't play and just queues up the next song, which also won't play. This happens for 4 songs, and then a new playlist is downloaded, 4 more songs are queued and skipped, then another playlist is downloaded. This continues for about 10-15 seconds until it just sits on the final song waiting to play.
Windows 10 Pro 64-bit

**Comment by x89codered89x** [comment]
Confirm I am having the same problem on Windows 8.1 64 bit using the August 2015 build.

**Comment by thedmd** [comment]
So you have any DShow filters installed or maybe you are using proxy?

**Comment by rgobo** [comment]
Same here, LAV splitter doesn't even start. I'm using a proxy but I don't think it's due to that because sometimes the same proxy works and then later skips, and changing proxies doesn't help. Sometimes it "fixes" by itself but lately, it doesn't work more often than it does.

**Comment by Zosoled** [comment]
I don't even know what DShow filters are, and I am not using a proxy.

**Comment by x89codered89x** [comment]
Again same as Zosoled

**Comment by QuixoticWolf** [comment]
Same issue on Windows 10 x64.

**Comment by zinefer** [comment]
Same issue on Windows 7 x64 ...

The [previous build](https://github.com/thedmd/pianobar-windows-binaries/tree/85fa96d74aa63f30a4f47c1a398a45f110f23abd) doesn't seem to suffer from the same issue.

**Comment by BananaWagon** [comment]
I downloaded the new version when the older version stopped working for me and I have the same issue as Zosoled. 
```
Welcome to pianobar (2013.05.19-win32)! Press ? for a list of commands.
(i) Login... Network error: TLS fingerprint mismatch.
```

New version does not play songs. No filters or codecs installed. I have reproduced this same issue on Win 7 x64 and Win 10 x64.

**Comment by thedmd** [comment]
I will investigate issue this weekend.

**Comment by thedmd** [comment]
@Zosoled: Please try 2015.12.05 release.

**Comment by rgobo** [comment]
I tried to test it but it seems like proxy is broken now, I can't start the service using any proxy config, even using those that work in older versions.

**Comment by zinefer** [comment]
Yay! Pianobar is working for me again!

Thanks! :+1:

**Comment by thedmd** [comment]
@rgobo proxy is a separate issue #13

**Comment by Zosoled** [comment]
Works for me, thanks!
