### ISSUE TITLE
Stops playing songs after receives new playlist

### ISSUE THREAD

**Issue by zinefer** [thedmd/pianobar-windows-binaries#18]
After this happens I hit pause/play and and force to choose the station again - after 2-3 songs I'll get a new playlist and it stops playing.

**Comment by 96fps** [comment]
It appears to lose track of what station was selected. 
I get about 4 songs, it fetches a new playlist, plays one song then stops, "No station selected". I can hit 's' and select my station again, but it's frustrating for something i usually just run in the background.

**Comment by zinefer** [comment]
After a few rounds of this I can't even select stations anymore.

**Comment by thedmd** [comment]
Try 2015.12.10 release.
