### ISSUE TITLE
switches and/or extended configuration options

### ISSUE THREAD

**Issue by ravensorrow** [thedmd/pianobar-windows-binaries#19]
Is it possible with PianoBar to pre-select the radio station to play? Say for example if I want a quick-mix of all my stationsto play or just station X....

**Comment by thedmd** [comment]
Yes, put this in your config file replacing <station_id> with real id. Ids are printed after station name when you select it, so you may copy it.

```autostart_station = <station_id>```

**Comment by thedmd** [comment]
I assume this is solved.
