### ISSUE TITLE
Stream ends after 5 songs

### ISSUE THREAD

**Issue by Zosoled** [thedmd/pianobar-windows-binaries#21]
After 5 songs have played, the program pauses as if waiting for a new playlist to be downloaded, sitting at 0:00 for the last song played. Commands can still be issued, and switching channels (even "switching" to the current one) will resume playback of a new song.

**Comment by thedmd** [comment]
Which version are you using?

**Comment by Zosoled** [comment]
2015.12.05

**Comment by thedmd** [comment]
Can you check if 2015.12.10 solved this issiue?

**Comment by shaymdev** [comment]
I had this issue on 2015.12.05. I just updated and 2015.12.10 fixed the issue for me.

**Comment by Zosoled** [comment]
Fixed in 2015.12.10.
