### ISSUE TITLE
Songs do not play (64 bit windows 10)

### ISSUE THREAD

**Issue by 96fps** [thedmd/pianobar-windows-binaries#22]
Logs in and gets playlist, but seconds after listing any track it moves on without making a noise. It goes on for half a dozen tracks before stopping. I can start the same sequence again by selecting a station, but again no music plays.

**Comment by thedmd** [comment]
Did you try 2015.12.10 release?

**Comment by 96fps** [comment]
yes, i have. It worked initially back in december, has not for a few weeks now. The only change has been me updating to windows 10. I've tried redownloading the latest build, but no success.

**Comment by 96fps** [comment]
Testing on another windows 10 install/harddrive on the same computer & same version of the executable, and it works fine, playing music normally.

Its really strange, the only difference is one install (where pianobar works) was updated from window 7, and the other (non-working one) from windows 8.1
Since it worked in 8.1, and nothing else doesn't work with 10, I don't know where the issue is.

Are there any dependancies i can try to update? A fresh install seems a little extreme.

Very strange.

**Comment by thedmd** [comment]
Indeed. Pianobar by default use Windows Media Foundation to play music. You may try Direct Show backend by placing:

player = ds

In your config file.
If that solve problem WMF backend should receive more investigation.

**Comment by 96fps** [comment]
:/ no change, but i just remembered the install i'm running was win8.1 N, and is not win10 N. Me thinks there are some missing media player functions.... looking into it now.

**Comment by 96fps** [comment]
no luck simply installing the "media feature pack", I'll look into backing up and re-installing some coming weekend.

**Comment by thedmd** [comment]
@96fps Do you still have this issue?

**Comment by 96fps** [comment]
No, a complete reinstall of windows seems to have fixed whatever was causing the issue. I was having other miscellaneous media-related oddities that also went away, such as trouble mounting MTP-cameras or errors when importing video into MS's Hyperlapse.

**Comment by thedmd** [comment]
I will close issue then.
