### ISSUE TITLE
Songs stop suddenly

### ISSUE THREAD

**Issue by zinefer** [thedmd/pianobar-windows-binaries#23]
Songs are often just stopping. Pause/play seems to do nothing. The only solution seems to be to skip to the next song. I think this might have to do with network issues while streaming the song.

**Comment by thedmd** [comment]
@zinefer 

Can you try to change playback backend to DirectShow? You can do that by putting this line in config:
```
player = ds
```

**Comment by thedmd** [comment]
Closed due to long inactivity.
