### ISSUE TITLE
Symantec False Positive?

### ISSUE THREAD

**Issue by philnagel** [thedmd/pianobar-windows-binaries#24]
Hello!

I am getting the pianobar.exe quarantined by the Symantec Endpoint Protection at my office. I am assuming this is a false positive, it appears to be based on their reputation management system. Basically, they have not seen the file before and therefore assume it is bad. Apparently, it can be submitted for analysis to be whitelisted here: https://submit.symantec.com/whitelist/isv/
Maybe that could be looked at.

**Comment by godofgrunts** [comment]
Just wanted to confirm that this is still an issue.

**Comment by thedmd** [comment]
I do not have not use Symantec products. So I will need a help with that. Can you @godofgrunts, @philnagel tell me when Symantec is reporting on pianobar? I have following options:
When did the detection you are reporting occur?
 A1 - When downloading or uploading a file
 A2 - While using an application
 A3 - When installing an application
 A4 - When browsing the web
 A5 - During a scheduled scan, or during a scan I requested
 A6 - When sending or receiving email
 A7 - While writing or reading files to/from a storage device
 A8 - Don't know, am unsure, or the options provided do not apply

**Comment by philnagel** [comment]
For me, it worked fine for a while, then the exe file suddenly was gone. so this was a case of A5, I believe.

**Comment by godofgrunts** [comment]
A1

On download, Symantec detected the executable as a [WS.Reputation.1](https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99). It's not very serious, but I did have my security manager yell at me.

**Comment by antonywu** [comment]
Webroot SecurityAnywhere basically quarantined the binary as Malware.Gen

**Comment by Pokaia** [comment]
I am having this issue with McAfee also.

**Comment by godofgrunts** [comment]
Here's an article with some information on how to submit multiple false positive reports:

http://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm

**Comment by thedmd** [comment]
@philnagel @godofgrunts @Pokaia @antonywu I made a false positive submits to all mentioned av software vendors. Now we are waiting for results.

**Comment by thedmd** [comment]
@antonywu 

Webroot SecurityAnywhere whitelisted pianobar. You can follow these steps to unquarantine player executable.

> Thank you for submitting your report. We have examined the logs from your system and found that the detected items were the result of a false positive, and are not a threat. We have updated our security definitions to address this. 
>
>You may un-quarantine and restore the file that was quarantined by the Webroot SecureAnywhere software if you have not already done so. To restore the file: 
>
>1. Open on the cog icon next to PC Security. 
>2. Click the Quarantine tab. 
>3. Click the check box next to the filename, then click Restore. 
>
>Now that this change is in effect, we request that you run another scan of your computer (click "Scan My Computer" on the main overview window). If the same detection occurs, please let us know immediately.

**Comment by thedmd** [comment]
@philnagel @godofgrunts 

Symantec also whitelisted pianobar.

>Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:
>
>        Filename: pianobar.exe
>        MD5: 0BB0104A7D769C7DFAE7985AF683C922
>        SHA256: 69D340721BF7A7EBC3EB1CE5619E6B7ACC1D3760032D8B20B5B50E93E22BFA2B
>        Result:         **Whitelisting for above file is taking effect from now on.**

**Comment by godofgrunts** [comment]
Works with Symantec. You can close as far as I'm concerned.

**Comment by thedmd** [comment]
Brilliant
